/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iuEscritorio;


public class MenuDesarrollo extends javax.swing.JFrame {

    /**
     * Creates new form MenuDesarrollo
     */
    public MenuDesarrollo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLoginAgenda = new javax.swing.JMenuItem();
        itemLoginAdministrador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU DESARROLLO");

        jMenu1.setText("Login");

        itemLoginAgenda.setText("Agenda");
        itemLoginAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(itemLoginAgenda);

        itemLoginAdministrador.setText("Administrador");
        itemLoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginAdministradorActionPerformed(evt);
            }
        });
        jMenu1.add(itemLoginAdministrador);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLoginAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginAgendaActionPerformed
        // TODO add your handling code here:
        new LoginMozo(this, false).setVisible(true);
    }//GEN-LAST:event_itemLoginAgendaActionPerformed

    private void itemLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginAdministradorActionPerformed
        // TODO add your handling code here:
         new LoginGestor(this, false).setVisible(true);
        
    }//GEN-LAST:event_itemLoginAdministradorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLoginAdministrador;
    private javax.swing.JMenuItem itemLoginAgenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
